#pragma once

#define GLE_VERSION_MAJOR 1
#define GLE_VERSION_MINOR 0
#define GLE_VERSION_PATCH 0
#define GLE_VERSION_BUILD 0

#define GLE_RC_FILE_VERSION 1, 0, 0, 0
#define GLE_RC_PRODUCT_VERSION 1, 0, 0, 0
#define GLE_RC_FILE_VERSION_STR "1.0.0.0"
#define GLE_RC_PRODUCT_VERSION_STR "1.0.0.0"
#define GLE_RC_PRODUCT_NAME "GLEngine"
#define GLE_RC_FILE_DESCRIPTION "GLEngine Editor"
#define GLE_RC_COMPANY_NAME "Greenland"
#define GLE_RC_LEGAL_COPYRIGHT "Copyright (C) 2026"
#define GLE_RC_INTERNAL_NAME "GLEngineNew"
#define GLE_RC_ORIGINAL_FILENAME "GLEngineNew.exe"
